trigger:
  - master
pool:
  name: Default  # Use your local agent

jobs:
  - job: ast_scan  # Define the job name correctly
    steps:
      - task: Checkmarx AST@3
        inputs:
          CheckmarxService: 'CxOne'
          projectName: '$(Build.Repository.Name)'
          branchName: '$(Build.SourceBranchName)'
          tenantName: 'sudha'
          additionalParams: '--ignore-policy'
