trigger: none

variables:
  - group: "CxOne DAST Variables"

pool:
  name: Default  # Use your local agent

jobs:
  - job: dast_scan
    displayName: 'Initiate DAST scan'
    steps:
      - script: |
          docker pull checkmarx/dast:latest
          docker run ^
            -e CX_APIKEY=$(CX_APIKEY) ^
            -v "C:\azure\vsts-agent-win-x64-4.248.0" ^
            checkmarx/dast:latest web ^
            --environment-id="573ceb9a-f003-40ba-88f9-d61fea148a4e" ^
            --config="C:\azure\vsts-agent-win-x64-4.248.0\_work\4\s\azure-pipelines.yml" ^
            --base-url=https://ind.ast.checkmarx.net/ ^
            --output=/dast_home/test_output ^
            --timeout=10000 ^
            --update-interval=10 ^
            --jvm-properties=-Xmx3G ^
            --log-level=info ^
            --verbose ^
            --retry=3 ^
            --retry-delay=20
        displayName: 'Run CxOne DAST via CMD'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish CxOne DAST Artifacts'
        inputs:
          targetPath: '$(Build.SourcesDirectory)/DAST-AZURE/test_output'
          artifact: 'CxOne DAST Artifacts'
