name: SAST scan
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  sast-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Enable PowerShell Script Execution
      #   run: Set-ExecutionPolicy Bypass -Scope Process -Force
      #   shell: powershell

      - name: Pull CxFlow Docker Image
        run: docker pull checkmarxts/cxflow:latest
        shell: powershell

      - name: Run Checkmarx CxFlow Scan
        run: |
          docker run --rm -v "$env:GITHUB_WORKSPACE:/app" checkmarxts/cxflow:latest `
            --add-host=host.docker.internal:192.168.110.89 `
            --checkmarx_url="${{ secrets.CX_URL }}" `
            --team="${{ secrets.CX_TEAM }}" `
            --checkmarx_username="${{ secrets.CX_USERNAME }}" `
            --checkmarx_password="${{ secrets.CX_PASSWORD }}" `
            --checkmarx_client_secret="${{ secrets.CX_CLIENT_SECRET2 }}" `
            --project="github_chartJS" `
            --app="github_chartJS" `
            --cx-project="github_chartJS"
        shell: powershell


# name: Checkmarx SAST Scan
# on:
#   push:
#     branches:
#       - main
#       - master
    
# jobs:
#   build:
#     runs-on: self-hosted
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name: Checkmarx CxFlow Action
#       uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.4 #Github Action version
#       with:
#         project: ${{ secrets.CX_PROJECT }} # <-- Insert Checkmarx SAST Project Name
#         team: ${{ secrets.CX_TEAM }}
#         checkmarx_url: ${{ secrets.CX_URL }} # To be stored in GitHub Secrets.
#         checkmarx_username: ${{ secrets.CX_USERNAME }} # To be stored in GitHub Secrets.
#         checkmarx_password: ${{ secrets.CX_PASSWORD }} # To be stored in GitHub Secrets.
#         checkmarx_client_secret: ${{ secrets.CX_CLIENT_SECRET2 }} # To be stored in GitHub Secrets.
#         break_build: false
#         scanners: sast
#         bug_tracker: Sarif
#         params: --namespace=${{ github.repository_owner }} --checkmarx.settings-override=true --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --cx-flow.filterSeverity --cx-flow.filterCategory  --checkmarx.disable-clubbing=true
#     - name: Upload SARIF file
#       uses: github/codeql-action/upload-sarif@v3
#       with:
#         sarif_file: cx.sarif
         
