# name: SAST scan

# on:
#   push:
#     branches: [ master, main ]
#   pull_request:
#     branches: [ master, main ]

# jobs:
#   sast-scan:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       # - name: Enable PowerShell Script Execution
#       #   run: Set-ExecutionPolicy Bypass -Scope Process -Force
#       #   shell: powershell

#       - name: Pull CxFlow Docker Image
#         run: docker pull checkmarxts/cxflow:latest
#         shell: powershell

#       - name: Run Checkmarx CxFlow Scan
#         run: |
#           docker run --rm -v "$env:GITHUB_WORKSPACE:/app" checkmarxts/cxflow:latest `
#             --add-host=host.docker.internal:192.168.110.89 `
#             --checkmarx_url="http://host.docker.internal:80" `
#             --team="/CxServer" `
#             --checkmarx_username="${{ secrets.CX_USERNAME }}" `
#             --checkmarx_password="${{ secrets.CX_PASSWORD }}" `
#             --checkmarx_client_secret="${{ secrets.CX_CLIENT_SECRET2 }}" `
#             --project="github_chartJS" `
#             --app="github_chartJS" `
#             --cx-project="github_chartJS"
#         shell: powershell


# This is a basic workflow to help you get started with Actions
name: CxFlow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: linux

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Cxflow Action
      - name: Checkmarx CxFlow Action
        # You may pin to the exact commit or the version.
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0-9.x
        with:
          # Provide Checkmarx URL
          checkmarx_url: ${{secrets.CX_URL}}
          # Provide team
          team: /CxServer/
          # Provide Checkmarx Username
          checkmarx_username: ${{secrets.CX_USERNAME}}
          # Provide Checkmarx Password
          checkmarx_password: ${{secrets.CX_PASSWORD}}
          # Provide Checkmarx Client Secret
          checkmarx_client_secret: ${{secrets.CHECKMARX_CLIENT_SECRET2}}
          # Select a Checkmarx Project
          project: DSVW-GitHub-action
          # Select an Application Name used by downstream bug tracker systems
          app: DSVW
         
