on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  sast-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull CxFlow Docker Image
        run: docker pull checkmarx/cx-flow
        shell: cmd  # Use cmd instead of pwsh

      - name: Run Checkmarx CxFlow Scan
        run: |
          docker run --rm -v "%GITHUB_WORKSPACE%:/app" checkmarx/cx-flow ^
            --cx-url="${{ secrets.CX_URL }}" ^
            --cx-team="/CxServer" ^
            --cx-username="${{ secrets.CX_USERNAME }}" ^
            --cx-password="${{ secrets.CX_PASSWORD }}" ^
            --cx-client-secret="${{ secrets.CX_CLIENT_SECRET }}" ^
            --cx-project="github_chartJS"
        shell: cmd  # Use cmd instead of pwsh
