name: SAST scan

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  sast-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Enable PowerShell Script Execution
      #   run: Set-ExecutionPolicy Bypass -Scope Process -Force
      #   shell: powershell

      - name: Pull CxFlow Docker Image
        run: docker pull checkmarx/cx-flow
        shell: powershell

      - name: Run Checkmarx CxFlow Scan
        run: |
          docker run --rm -v "$env:GITHUB_WORKSPACE:/app" checkmarx/cx-flow `
            --add-host=host.docker.internal:192.168.110.89
            --checkmarx_url="http://host.docker.internal" `
            --team="/CxServer" `
            --checkmarx_username="${{ secrets.CX_USERNAME }}" `
            --checkmarx_password="${{ secrets.CX_PASSWORD }}" `
            --checkmarx_client_secret="${{ secrets.CX_CLIENT_SECRET2 }}" `
            --project="github_chartJS" `
            --app="github_chartJS" `
            --cx-project="github_chartJS"
        shell: powershell
